# docker-compose.yml
networks:
  frontend:
  backend:

secrets:
  db_password:
    file: db_password.txt

services:
  productservice:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "./config:/config"
      - "./src:/code"
    secrets:
      - db_password
    networks:
      - frontend
      - backend
    ports:
      - "5678:5678"
    environment:
      - DEBUG=True

  web:
    build: ngnix
    ports:
      - "80:80"
    networks:
      - frontend

  db:
    image: mysql
    command: "--init-file /data/application/init.sql --default-authentication-plugin=mysql_native_password"
    volumes:
      - "./db/init.sql:/data/application/init.sql"
      # If you want persist your database uncomment line below, make sure write permission there
      - "db-volume:/var/lib/mysql"
    environment:
      - MYSQL_ROOT_PASSWORD=password
    networks:
      - backend
      
volumes:
  db-volume: