# docker-compose.yml
services:
  productservice:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "./config:/config"
  web:
    build: ngnix
    ports:
      - "80:80"
  db:
    image: mysql
    command: "--init-file /data/application/init.sql --default-authentication-plugin=mysql_native_password"
    volumes:
      - "./db/init.sql:/data/application/init.sql"
      # If you want persist your database uncomment line below, make sure write permission there
      - "db-volume:/var/lib/mysql"
    environment:
      - MYSQL_ROOT_PASSWORD=password
volumes:
  db-volume: